import test from 'node:test';
import assert from 'node:assert/strict';
import { calcularCambioObservado, calcularEscenarioSoftware, resumirIngresosPrograma, validarIniciativa, validarResultado, leerRegistroValor } from '../../src/features/valor/valorEconomico.js';
test('El cambio observado descuenta costo y no produce un total de atribución',()=>{assert.equal(calcularCambioObservado({indicador:'utilidad_bruta',base:100,dias:7,resultado:{observado:180,costo:20,dias:7}}),60);assert.equal(calcularCambioObservado({indicador:'gasto',base:100,dias:7,resultado:{observado:70,costo:10,dias:7}}),20);});
test('No compara duraciones distintas ni convierte costos ausentes en cero',()=>{assert.equal(calcularCambioObservado({indicador:'gasto',base:100,dias:7,resultado:{observado:50,costo:'',dias:7}}),null);assert.equal(calcularCambioObservado({indicador:'gasto',base:100,dias:7,resultado:{observado:50,costo:0,dias:14}}),null);assert.equal(calcularCambioObservado({indicador:'otro',base:100,dias:7,resultado:{observado:50,costo:0,dias:7}}),null);});
test('Cobros de software excluyen ventas de tienda, cancelados, tipos erróneos y pendientes',()=>{const m=(id,concept,amount,movement_type='ENTRADA',status='Revisado')=>({id,concept,amount,movement_type,status});const r=resumirIngresosPrograma([m('1','Venta tienda',1000),m('2','[MONYS LICENCIA] Cliente A',500),m('3','[MONYS IMPLEMENTACION] Cliente B',100,'ENTRADA','Cancelado'),m('4','[MONYS LICENCIA] Cliente C',200,'ENTRADA','Pendiente de revisión'),m('5','[MONYS COSTO] Soporte',50,'SALIDA'),m('6','[MONYS COSTO] Error',10),m('7','[MONYS LICENCIA] Error',30,'SALIDA')]);assert.equal(r.cobrosDocumentados,500);assert.equal(r.costosDocumentados,50);assert.equal(r.pendientes,1);assert.equal(r.registros.length,3);});
test('Escenario distingue faltantes, ceros y contribución insuficiente',()=>{assert.equal(calcularEscenarioSoftware({clientes:'',precio:100,costoFijo:100,costoCliente:10}),null);assert.deepEqual(calcularEscenarioSoftware({clientes:10,precio:100,costoFijo:200,costoCliente:20}),{ingresosMensuales:1000,costosMensuales:400,resultadoMensual:600,clientesEquilibrio:3});assert.equal(calcularEscenarioSoftware({clientes:10,precio:50,costoFijo:200,costoCliente:50}).clientesEquilibrio,null);assert.equal(calcularEscenarioSoftware({clientes:1.5,precio:100,costoFijo:0,costoCliente:0}),null);});
test('Requiere referencia de evidencia y aprendizaje para revisar resultado',()=>{const base={dias:7};assert.throws(()=>validarResultado({observado:100,costo:0,dias:7,evidencia:'',aprendizaje:'Aprendí'},base));assert.throws(()=>validarResultado({observado:100,costo:0,dias:14,evidencia:'Reporte',aprendizaje:'Aprendí'},base));assert.equal(validarResultado({observado:100,costo:0,dias:7,evidencia:'Reporte',aprendizaje:'Aprendí'},base).costo,0);});
test('Valida línea base y fecha; tolera resultados de tareas ajenas sin interpretarlos como valor',()=>{const d={titulo:'Prueba',hipotesis:'Rotar',indicador:'utilidad_bruta',base:0,dias:7,fuenteBase:'SICAR',fecha:'2026-10-15'};assert.equal(validarIniciativa(d).base,0);assert.throws(()=>validarIniciativa({...d,fecha:'2026-02-30'}));assert.throws(()=>validarIniciativa({...d,base:''}));assert.equal(leerRegistroValor({resultado:'No es una prueba'}),null);assert.equal(leerRegistroValor({resultado:JSON.stringify({tipo:'MARKETING'})}),null);});
