import { useState } from 'react';
import { calcularEquilibrioDiario } from '../../utils/equilibrioDiario';
const dinero=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(v);
const campos=[['gastosFijos','Gastos fijos del mes (MXN)'],['margenBruto','Margen bruto previsto (%)'],['variablePorcentaje','Otros costos variables sobre ventas (%)'],['diasAbiertos','Días que abrirás en el mes'],['deuda','Pagos de deuda del mes (MXN)'],['ventaPrevista','Venta prevista del mes (MXN)']];
export default function EquilibrioDiario(){
 const [datos,setDatos]=useState(Object.fromEntries(campos.map(([c])=>[c,''])));
 const [mes,setMes]=useState('');
 const r=calcularEquilibrioDiario(datos);
 return <section className="junta" aria-label="Simulador de equilibrio diario"><header><div><span className="junta-label">ESTIMACIÓN · ESCENARIO MANUAL</span><h2>¿Cuánto necesitas vender al día?</h2><p>Define un mismo mes y alcance para todos los importes.</p></div></header><label>Mes del escenario<input type="month" value={mes} onChange={e=>setMes(e.target.value)}/></label><p>Gastos fijos: renta, nómina fija y demás operación. El margen bruto ya descuenta el costo del producto. En costos variables añade comisiones, cobro con tarjeta y otros porcentajes que aún no estén descontados. Deuda: principal e intereses; exclúyelos de gastos fijos para no contarlos dos veces.</p><div className="junta-columns">{campos.map(([c,label])=><label key={c}>{label}<input type="number" min="0" max={c==='diasAbiertos'?31:c.includes('Porcentaje')||c==='margenBruto'?100:undefined} step={c==='diasAbiertos'?1:0.01} value={datos[c]} placeholder="Por completar" onChange={e=>setDatos(v=>({...v,[c]:e.target.value}))}/></label>)}</div>{!mes?<p role="status">Selecciona el mes para calcular el escenario.</p>:!r.calculable?<p role="status">{r.motivo}</p>:<><div className="junta-asientos"><article><span className="junta-label">CUBRIR OPERACIÓN</span><h3>{dinero(r.operacionDiaria)} / día abierto</h3><p>{dinero(r.operacion)} en el mes</p></article><article><span className="junta-label">OPERACIÓN + DEUDA</span><h3>{dinero(r.cajaDiaria)} / día abierto</h3><p>{dinero(r.caja)} en el mes</p></article></div><p>Margen de contribución estimado: {(r.contribucion*100).toFixed(1)}%. Brecha contra la venta prevista: {dinero(r.brechaOperacion)} para operación y {dinero(r.brechaCaja)} incluyendo deuda.</p><p role="status">{r.brechaCaja>0?'El escenario no alcanza a cubrir operación y deuda. Revisa margen, gastos y compromisos antes de aumentar inversión.':'La venta prevista cubriría estos compromisos si se cumple el margen y se cobran las ventas.'}</p><details><summary>Cómo se calcula y qué falta</summary><p>Ventas necesarias = compromisos ÷ margen de contribución. Meta diaria = ventas necesarias ÷ días abiertos. El pago de principal afecta caja; no es gasto contable. No incluye desfases de cobro, compras de inventario, impuestos adicionales, inversión ni saldos iniciales: revísalos en el flujo de 13 semanas. No representa utilidad neta ni efectivo disponible.</p></details></>}<p>Este escenario permanece en esta pantalla; no se guarda ni sincroniza. Los importes son estimaciones capturadas por ti, no saldos bancarios verificados.</p></section>;
}
