import { useState } from 'react';
import DirectorFinanciero from '../inteligencia/components/director-finanzas/DirectorFinanciero';
import TesoreriaPage from '../tesoreria/pages/TesoreriaPage';
import RevisionEstadoBancario from '../tesoreria/components/RevisionEstadoBancario';
import './CentroFinanciero.css';
export default function CentroFinanciero({ datosDashboard, sucursalesDashboard, movimientos, formatoDinero, onMovimientoGuardado, onCambiarEstado, onAbrirImportador, volverAlDashboard }) {
 const [tab,setTab]=useState('bancos');
 return <main className="centro-financiero"><header className="finanzas-portada"><div className="finanzas-top"><span>MONYS OS · DIRECCIÓN FINANCIERA</span><button onClick={volverAlDashboard}>Volver al inicio</button></div><h1>Tu dinero. Tus decisiones.</h1><p>Revisa el banco, controla los movimientos y planea cómo sostener tu negocio.</p><div className="finanzas-ruta"><span>01 · Verificar dinero</span><span>02 · Explicar destino</span><span>03 · Planear pagos y ventas</span></div></header><nav className="finanzas-tabs" aria-label="Áreas financieras">{[['bancos','Bancos y aclaraciones','Estados, evidencia y destino'],['control','Movimientos','Entradas, salidas y revisión'],['plan','Planeación financiera','Equilibrio, proveedores y flujo']].map(([id,titulo,detalle])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}><b>{titulo}</b><small>{detalle}</small></button>)}</nav><div className="finanzas-fuentes"><p><b>Estado de los datos:</b> los reportes enviados al chat no se importan automáticamente a MONYS. Los borradores bancarios se guardan en este dispositivo; las cifras del negocio usan las importaciones registradas.</p><button onClick={onAbrirImportador}>Cargar reportes del negocio →</button></div><section className="finanzas-evidencias"><h2>Gastos: tres fuentes, un solo registro</h2><div className="finanzas-tabs"><article><b>Estados bancarios</b><p>Pagos y cobros comprobados por el banco. Revisa el destino en Bancos y aclaraciones.</p></article><article><b>Movimientos de caja SICAR</b><p>Entradas y salidas de tienda. Importa el reporte y revisa los movimientos registrados.</p></article><article><b>WhatsApp y comprobantes</b><p>Explican para qué se pagó y a quién. Falta cruzarlos con banco y caja antes de sumar gastos.</p></article></div><p>El mismo pago puede aparecer en varias fuentes. La conciliación entre fuentes está pendiente; no se suman automáticamente para calcular utilidad.</p></section><p className="finanzas-recordatorio">Antes de cambiar de área, guarda o descarga las aclaraciones que hayas editado.</p>{tab==='bancos'&&<RevisionEstadoBancario movimientos={movimientos}/>}{tab==='control'&&<TesoreriaPage ocultarRevisionBancaria volverAlDashboard={volverAlDashboard} onMovimientoGuardado={onMovimientoGuardado} movimientos={movimientos} formatoDinero={formatoDinero} onCambiarEstado={onCambiarEstado}/>}{tab==='plan'&&<DirectorFinanciero datosDashboard={datosDashboard} sucursalesDashboard={sucursalesDashboard} movimientos={movimientos} onAbrirImportador={onAbrirImportador}/>}</main>;
}
